import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import UserAccount from "@/components/UserAccount";
import Link from "next/link";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50">

        {/* Top Navbar */}
        <header className="bg-white border-b border-gray-200 text-black">
          <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">

            {/* Logo / App Name */}
            <Link href="/" className="font-semibold text-lg">
              CarBuyingPower
            </Link>

            {/* Account */}
            <div>
              <UserAccount />
            </div>

          </div>
        </header>

        {/* Page Content */}
        <main className="max-w-6xl mx-auto px-6 py-8">
          {children}
        </main>

      </body>
    </html>
  );
}
